# Generated by Django 5.0.3 on 2026-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_document_id_alter_education_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="opportunity_type",
            field=models.CharField(
                choices=[
                    ("ATTACHMENT", "Industrial Attachment"),
                    ("INTERNSHIP", "Youth Internship"),
                    ("NONE", "Not Selected"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("TRANSCRIPT", "Transcripts"),
                    ("NATIONAL_ID", "National ID"),
                    ("RESUME", "Resume/CV"),
                    ("COVER_LETTER", "Cover Letter"),
                    ("INSTITUTION_INTRO", "Introduction Letter from Institution"),
                    ("GOOD_CONDUCT", "Certificate of Good Conduct"),
                    ("STUDENT_INSURANCE", "Student Insurance Cover"),
                    ("STUDENT_ID", "Copy of Student ID"),
                    ("NEXT_OF_KIN_ID", "Copy of Next of Kin (ID & Phone)"),
                    ("KRA_PIN", "KRA PIN Certificate"),
                    ("SHA_CARD", "SHA Card"),
                    ("NSSF_CARD", "NSSF Card"),
                    ("BIRTH_CERT", "Birth Certificate"),
                    ("ACADEMIC_CERT", "Academic Certificates"),
                    ("SECRETS_ACT_FORM", "Official Secrets Act Form"),
                    ("PSIP_FORM", "PSIP Intern Biodata Form"),
                    ("PASSPORT_PHOTOS", "Two Colour Passport Photos (PDF)"),
                    ("ATM_CARD", "ATM Card / Bank Details"),
                ],
                max_length=20,
            ),
        ),
    ]
