# Generated by Django 6.0.3 on 2026-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_opportunity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_number",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="kra_pin",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="opportunity_type",
            field=models.CharField(
                choices=[
                    ("ATTACHMENT", "Industrial Attachment"),
                    ("INTERNSHIP", "Youth Internship"),
                    ("NONE", "Not Selected"),
                ],
                db_index=True,
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("APPLICANT", "Applicant")],
                db_index=True,
                default="APPLICANT",
                max_length=20,
            ),
        ),
    ]
