# Generated by Django 5.0.3 on 2026-04-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_id_number_alter_profile_kra_pin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="opportunity_type",
            field=models.CharField(
                choices=[("ATTACHMENT", "Industrial Attachment")],
                db_index=True,
                default="ATTACHMENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR Manager"),
                    ("APPLICANT", "Applicant"),
                ],
                db_index=True,
                default="APPLICANT",
                max_length=20,
            ),
        ),
    ]
