# Generated by Django 5.0.3 on 2026-06-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_opportunity_type_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="institution",
            new_name="institution_name",
        ),
        migrations.RenameField(
            model_name="education",
            old_name="is_current",
            new_name="current",
        ),
    ]
