# Generated by Django 5.0.3 on 2026-06-29 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_education_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("TRANSCRIPT", "Transcripts"),
                    ("NATIONAL_ID", "National ID"),
                    ("RESUME", "Resume/CV"),
                    ("COVER_LETTER", "Cover Letter"),
                    ("INSTITUTION_INTRO", "Introduction Letter from Institution"),
                    ("GOOD_CONDUCT", "Certificate of Good Conduct"),
                    ("STUDENT_INSURANCE", "Student Insurance Cover"),
                    ("STUDENT_ID", "Copy of Student ID"),
                    ("NEXT_OF_KIN_ID", "Copy of Next of Kin (ID & Phone)"),
                    ("KRA_PIN", "KRA PIN Certificate"),
                    ("SHA_CARD", "SHA Card"),
                    ("NSSF_CARD", "NSSF Card"),
                    ("BIRTH_CERT", "Birth Certificate"),
                    ("ACADEMIC_CERT", "Academic Certificates"),
                    ("SECRETS_ACT_FORM", "Official Secrets Act Form"),
                    ("PSIP_FORM", "PSIP Intern Biodata Form"),
                    ("PASSPORT_PHOTOS", "Two Colour Passport Photos (PDF)"),
                    ("ATM_CARD", "ATM Card / Bank Details"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="responsibilities",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="training",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    django.core.validators.MaxValueValidator(2100),
                ]
            ),
        ),
    ]
