# Generated by Django 5.0.3 on 2026-03-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ats_score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
