# Generated by Django 6.0.3 on 2026-04-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_application_id_alter_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("REJECTED", "Rejected"),
                    ("HIRED", "Hired"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("INTERNSHIP", "Internship"),
                    ("ATTACHMENT", "Attachment"),
                    ("JOB_OPENING", "Job Opening"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
