# Generated by Django 5.0.3 on 2026-04-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_application_applied_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="ats_score",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0.0, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("ATTACHMENT", "Attachment"), ("JOB_OPENING", "Job Opening")],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
