# Generated by Django 5.0.3 on 2026-06-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_alter_application_ats_score_alter_job_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REVIEWED", "Reviewed"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("REJECTED", "Rejected"),
                    ("HIRED", "Hired"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
